version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v5-dependencies-{{ checksum "package.json" }}

      - run: npm install @syncano/cli@canary
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v5-dependencies-{{ checksum "package.json" }}

      - save_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  test:
    name: Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v5-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run test

      - store_artifacts:
          path: ~/repo/test/.results

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
